version: '2'
services:
  web:
    build: .
    # image: openjdk:8-jdk-alpine
    ports:
      - "80:8080"
    volumes:
      # where your project code lives
      - "/Users/workken/Downloads/demo/hello-world:/home"
    restart: always
volumes:
  local_data: